project:
  type: website
  output-dir: _site

website:
  title: "One Tool to Rule Them All"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: foundations/quarto-intro.qmd
        text: Foundations
      - href: use-cases/lab-notebook.qmd
        text: Academic Use Cases
      - href: advanced/templates-and-extensions.qmd
        text: Advanced Topics
  sidebar:
    logo: false
    style: floating
    search: true
    collapse-level: 1
    contents:
      - section: "Foundations"
        contents:
          - foundations/quarto-intro.qmd
          - foundations/markdown-intro.qmd
          - foundations/yaml-intro.qmd
          - foundations/installing-quarto.qmd
      - section: "Academic Use Cases"
        contents:
          - use-cases/lab-notebook.qmd
          - exercises/lab-notebook-exercise.qmd
          - use-cases/manuscripts.qmd
          - exercises/manuscripts-exercise.qmd
          - use-cases/presentations.qmd
          - exercises/presentations-exercise.qmd
          - use-cases/websites.qmd
          - exercises/websites-exercise.qmd
          - use-cases/dashboards.qmd
          - exercises/dashboards-exercise.qmd
      - section: "Advanced Topics"
        contents:
          - advanced/templates-and-extensions.qmd
          - advanced/brand-yml.qmd
brand: 
  light: light-brand.yml
  dark: dark-brand.yml
format:
  html:
    theme: styles.scss
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true

execute:
  echo: true
  warning: false
  message: false
