project:
  output-dir: _site
  resources:
    - assets/publications.yaml
    - assets/publication_yearly.ejs
    - data/restoration-sites.csv
    - data/restoration-scenarios.csv

website:
  title: ""
  page-navigation: false
  repo-url: https://github.com/iat-dml/quarto-workshop
  repo-actions: [edit]
  twitter-card:
    image: assets/website-screenshots/workshop-website-light.png
    title: "One Tool to *Rule Them All: Quarto for Documentation, Presentations, Manuscripts and Outreach"
    description: "A guided workshop demonstrating how to use Quarto to create academic websites, presentations, manuscripts and outreach materials."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: foundations/quarto-intro.qmd
        text: Foundations
      - href: use-cases/research-diary.qmd
        text: Academic Use Cases
      - href: advanced/templates-and-extensions.qmd
        text: Advanced Topics
  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - section: "Foundations"
        contents:
          - foundations/quarto-intro.qmd
          - foundations/markdown-intro.qmd
          - foundations/yaml-intro.qmd
          - foundations/installing-quarto.qmd
      - section: "Academic Use Cases"
        contents:
          - text: "Documenting Research in Progress"
            href: use-cases/research-diary.qmd
          - text: "   ↳ Exercise"
            href: exercises/research-diary-exercise.qmd
          - text: "Writing Manuscripts"
            href: use-cases/manuscripts.qmd
          - text: "   ↳ Exercise"
            href: exercises/manuscripts-exercise.qmd
          - text: "Creating Presentations"
            href: use-cases/presentations.qmd
          - text: "   ↳ Exercise"
            href: exercises/presentations-exercise.qmd
          - text: "Creating Project and Personal Websites"
            href: use-cases/websites.qmd
          - text: "   ↳ Exercise"
            href: exercises/websites-exercise.qmd
          - text: "Dashboards"
            href: use-cases/dashboards.qmd
          - text: "   ↳ Exercise"
            href: exercises/dashboards-exercise.qmd
      - section: "Advanced Topics"
        contents:
          - advanced/templates-and-extensions.qmd
          - advanced/brand-yml.qmd
          - advanced/multi-lingual-outputs.qmd
          - advanced/invites.qmd
          - advanced/ai-assistance.qmd
      - section: "Go Further"
        href: go-further.qmd
        contents:
          - go-further.qmd

format:
  html:
    theme: styles.scss
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    smooth-scroll: true
